name: i2c-snap
version: "0.1" 
summary: i2c snap app
description: >
    Example i2c-mqtt snap app
confinement: devmode
grade: devel

apps:
  i2c-snap:
    command: mqtt.py

parts:
  i2c-snap:
    plugin: python
    source: .
    stage-packages:
    - python-smbus
architectures: [armhf]
    
